---
- name: Verify
  hosts: all
  vars:
    clang_versions:
      - "5.0"
      - "6.0"
      - "7"
      - "11"
      - "12"
  tasks:
    - name: Stat clang binaries
      ansible.builtin.stat:
        path: "/usr/lib/llvm-{{ item }}/bin/clang"
      register: clang_binaries
      loop: "{{ clang_versions }}"

    - name: Assert that clang was installed correctly
      ansible.builtin.assert:
        that:
          - item.stat.exists
          - item.stat.isreg
          - item.stat.mode == "0755"
      loop: "{{ clang_binaries.results }}"

    - name: Stat clang symlinks
      ansible.builtin.stat:
        path: "/usr/bin/clang-{{ item }}"
      register: clang_symlinks
      loop: "{{ clang_versions }}"

    - name: Assert that clang symlinks were installed correctly
      ansible.builtin.assert:
        that:
          - item.stat.exists
          - item.stat.islnk
      loop: "{{ clang_symlinks.results }}"
